version: "3"

volumes:
    datavolume:
        driver: local

services:
    api:
        container_name: api
        image: nginx:latest
        hostname: api
        ports:
        - "8080:80"
        volumes:
        - ./api:/api
        - ./nginx.conf:/etc/nginx/conf.d/default.conf
        links:
        - php
        networks:
        - demo
    php:
        container_name: php
        hostname: php
        build:
            context: .
            dockerfile: PhpDockerfile
        env_file:
          - .env
        volumes:
        - ./api:/api
        depends_on:
        - postgres
        links:
        - postgres
        networks:
        - demo
    postgres:
        container_name: postgres
        image: postgres
        hostname: postgres
        restart: always
        environment:
            POSTGRES_PASSWORD: develop123
            POSTGRES_USER: develop
            POSTGRES_DB: demo
        ports:
        - "5432:5432"
        volumes:
        - datavolume:/var/lib/postgresql/data
        networks:
        - demo
    composer:
        image: composer
        volumes:
        - ./api:/api
        working_dir: /api
    mailhog:
        container_name: mailhog
        build:
            context: .
            dockerfile: MailhogDockerfile
        ports:
        - "8025:8025"
        - "1025:1025"
        networks:
        - demo
networks:
    demo:
        external: true
